[versions]
# Apache Commons
commons_compress="1.23.0"
zstd="1.5.5-3"

# Utilites
fastutil="8.5.12"
jopt="5.0.4"

# Logger
slf4j="2.0.7"
logback="1.4.6"

[libraries]
# Apache Commons
commons_compress = { module = "org.apache.commons:commons-compress", version.ref = "commons_compress" }
zstd = { module = "com.github.luben:zstd-jni", version.ref = "zstd" }

# Utilties
fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }
jopt = { module = "net.sf.jopt-simple:jopt-simple", version.ref = "jopt" }

# Logger
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

[bundles]
commons = ["commons_compress", "zstd"]
utils = ["fastutil", "jopt"]
logger = ["logback", "slf4j"]
