/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
	// Apply the application plugin to add support for building a CLI application in Java.
	application
	id("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories {
	// Use Maven Central for resolving dependencies.
	mavenCentral()
}

dependencies {
	// This dependency is used by the application.
	implementation("com.google.guava:guava:31.1-jre")
	implementation(libs.bundles.commons)
	implementation(libs.bundles.utils)
	implementation(libs.bundles.logger)
}

testing {
	suites {
		// Configure the built-in test suite
		val test by getting(JvmTestSuite::class) {
			// Use TestNG test framework
			useTestNG("7.5")
		}
	}
}

application {
	// Define the main class for the application.
	mainClass.set("gay.ampflower.bundler.App")
}

tasks {
	withType<JavaCompile> {
		options.compilerArgs.addAll(listOf("-Xlint:unchecked", "-Xlint:deprecation"))
	}
}
